### PR TITLE
Update for permanent gaze attacks

### PR DESCRIPTION
**Pull request by KenshiDRK**
It also includes a feature to turn even if you are not the target of the
gaze .

### CODE REVIEW

**Comment by smd111** [comment]
ok sence im assuming you tried and tested the code fully on multiple mobs
i will accept it but there are a few thing ill teach you about how to code better
--give me a day or so to verify that its working for my self

1 try to use each check only once in each function(if you can)
Example:
your code(line 79):

```
            if packet['Category'] == 7 and check_target_id(packet) then
                if check_target_action(packet) then
                    ...
                end
            elseif packet['Category'] == 7 and check_facing() then
                if check_target_action(packet) then
                    ...
                end
```

a better way:

```
            if packet['Category'] == 7 and (check_target_id(packet) or check_facing()) and check_target_action(packet) then
                    ...
            end
```

and then
yours(line 66):

```
            if settings.gaze_watch and gaze_attacks[v] then
                return true
            elseif settings.perm_gaze_watch and perm_gaze_attacks[v] then
                return true
            end
```

better:

```
            if (settings.gaze_watch and gaze_attacks[v]) or (settings.perm_gaze_watch and perm_gaze_attacks[v]) then
                return true
            end
```

with just those two changes it saved 10 lines and at lest 2 checks

also this function is useless to keep except for debuging
function PrintSomething

and check_facing() only check to see if your main target is with in your 180 degree view

and in packet 0x028 the data for when a long term gaze attack falls should be there(but not sure it could be 0x029)
--is there a chat line that pops up when the perm gaze falls off??

also you need to release gaze when you change targets

**Comment by KenshiDRK** [comment]
thx for the suggestions to simplify the code, I'll change them now. 
The check_facing() checks if your target is between 90 degrees of your view and if you are between 90 degrees of the target view.
There is no message in the chat log, the only packet that maybe could contain that info is the npc update packet that might change their model.

A good mob to test is the Tutewehiwehi in morimar.

**Comment by smd111** [comment]
there has to be a packet that changes the glare effect to off

**Comment by KenshiDRK** [comment]
From what I know only effect that you apply are send to you via 0x029 when they wear off, as it is a effect that is applied by the mob himself, I'm pretty sure it is kept server side.

**Comment by smd111** [comment]
no most of the long time gazes have a visual effect to show its active(mob's eyes,body etc.)

check to see if anything in this changes when gaze turns off
windower.ffxi.get_mob_by_id(trigered_actor)--mob info
or
in packet 0x00E --NPC Update
--it can also be used to tell when a specific mob dies
--im betting on it being in Mask,Status, or one of the unknown's

as i said before this is the biggest reason i dont include a turn for long time gazes

im sorry im giving most of this to you but im not at home right now and wont be for a few days

**Comment by KenshiDRK** [comment]
model doesn't change but 0x00E in _unknown4 seems to have the info, exactly the byte 42 or 0x2A.
when mob is normal the value is 0x04, on grim glower is 0x05, and on oppressive glare is 0x06. Now need to check the caturaes but probably is 0x06 too due to blue eyes.

**Comment by smd111** [comment]
if thats true then it might be a binary trigger??
because
4 = 100
5 = 101
6 = 110 
im betting
7 = 111 -- red eye glow

**Comment by KenshiDRK** [comment]
yes it is, but have to be carefull cause caturaes has 2 effects, the eyes and the shield.
On caturaes =
4 = 100 (normal)
5 = 101 (eyes gaze)
6 = 110 ? still need to check but probably shield
7 = 111 eyes + shield

**Comment by smd111** [comment]
what do the caturaes eyes look like??

**Comment by KenshiDRK** [comment]
Confirmed 6 = 110 is shield on caturaes

**Comment by KenshiDRK** [comment]
they get blue eyes when they have gaze on

**Comment by smd111** [comment]
what about shield -- yellow??
and then eyes and shield -- red??

**Comment by KenshiDRK** [comment]
https://cdn.bg-wiki.com/images/0/0d/Pil.jpg

**Comment by smd111** [comment]
so thoes switches are different by mob

**Comment by KenshiDRK** [comment]
probably differents between types of mobs, cause the complete _unknown4 was exactly the same on a normal green peiste than the tutewehiwehi when no eyes were on.

**Comment by smd111** [comment]
so it would be model_effect 1 and model_effect 2
and probly if there are more thay go back in the packet

**Comment by smd111** [comment]
one question does 0x2A change before or after the ablily activates
i.e.
0x2A change
readys ability
uses ability
or
readys ability
0x2A change
uses ability
or
readys ability
uses ability
0x2A change

**Comment by KenshiDRK** [comment]
its after the ability has been used, the 0x2A changes and then the model changes with it.

**Comment by smd111** [comment]
ok

**Comment by KenshiDRK** [comment]
Got the addon working and it changes eyes

https://gist.github.com/KenshiDRK/ca58edef5e122457137dc96e977d6810

change the index for the mob you want to change the effect and change_effect 5 for yellow eyes 6 for blue, 7 is still blue eyes but 8 made no eyes effect (use only on peistes and caturaes, you might crash
with others)

**Comment by smd111** [comment]
thats cool so it does do what was found

now we need to figure out how to use it

**Comment by KenshiDRK** [comment]
yea and put gaze_check to another level :)

**Comment by smd111** [comment]
somthing like

```
    if id == 0x00E then
        local packet = packets.parse('incoming', data)
        if packet.Index == trigered_actor and gaze then
            if data:unpack('b8', 43) == 4 then
                gaze = false
            end
        end
    end
```

but you would still need a way to see if the mob dies
to set  gaze = false

**Comment by smd111** [comment]
and because your doing so much you can add this to the tool
_addon.author = 'smd111/KenshiDRK'
or what ever name you want to be know as

**Comment by KenshiDRK** [comment]
yea but we should add checks so it doesn't interfere with other abilities like torpefiying charge that will be done while that byte is 4 and to not turn back if the torpefying charge is done while the eyes are glowing.

**Comment by smd111** [comment]
i though of that as well something like

```
            if packet['Category'] == 7 and check_target_action(packet) then
                if check_target_id(packet) then
                    gaze = true
                    trigered_actor = packet['Actor']
                    windower.ffxi.turn(windower.ffxi.get_mob_by_id(packet['Actor']).facing)
                elseif check_facing() then
                    perm_gaze = true
                    perm_trigered_actor = packet['Actor']
                    windower.ffxi.turn(windower.ffxi.get_mob_by_id(packet['Actor']).facing)
                end
            elseif packet['Actor'] == trigered_actor and packet['Category'] == 11 and gaze and not perm_gaze then
                if settings.gaze_watch and gaze_attacks[packet['Param']] then
                    gaze = false
                    trigered_actor = 0
                    windower.ffxi.turn:schedule(1,windower.ffxi.get_mob_by_target('t').facing+math.pi)
```

**Comment by smd111** [comment]
i also have a question does 0x2A change when non perm gazes are activated?? if that do that would be cool as well because then we would only need to watch packet  0x00E for gaze end

i cant remember if there eyes change for fast gaze attacks

**Comment by KenshiDRK** [comment]
No, cause it only changes if the model of the mob changes, if the move doesn't cause the model to change in appearence it won't change. Also the code you posted will have a problem with grim glower cause it has the player as target id. I think the check should be added in the check_target_action() function.

**Comment by smd111** [comment]
can you try somthing like this for per gazes??

```
    if id == 0x00E then
        local packet = packets.parse('incoming', data)
        local target = windower.ffxi.get_mob_by_target('t')
        if packet.Index == target.Index then
            local effect = data:unpack('b8', 43)
            if data:unpack('b8', 43) > 4 then
                windower.ffxi.turn(target.facing)
            elseif data:unpack('b8', 43) == 4 then
                windower.ffxi.turn(target.facing+math.pi)
            end
        end
    end
```

to see if it looks away in time??

**Comment by KenshiDRK** [comment]
Thats what I though:
ew posting code is a nightmare here

**Comment by smd111** [comment]
if your going to post code here use 3 ` (its the ~ key) before and after your code

but if the code i posted above works we could do something like this
because unless your aoeing thay can build the tp needed to use the gaze attack(at lest i think)

```
windower.register_event('incoming chunk', function(id, data, modified, injected, blocked)
    if id == 0x028 then
        local packet = packets.parse('incoming', data)
        if windower.ffxi.get_player().in_combat and windower.ffxi.get_mob_by_target('t') then
            if packet['Category'] == 7 and check_target_action(packet) then
                if check_target_id(packet) then
                    gaze = true
                    trigered_actor = packet['Actor']
                end
            elseif packet['Actor'] == trigered_actor and packet['Category'] == 11 and gaze then
                if settings.gaze_watch and gaze_attacks[packet['Param']] then
                    gaze = false
                    trigered_actor = 0
                end
            end
        end
    end
    if id == 0x00E then
        local packet = packets.parse('incoming', data)
        if packet.Index == windower.ffxi.get_mob_by_target('t').Index then
            local effect = data:unpack('b8', 43)
            if data:unpack('b8', 43) > 4 then
                perm_gaze = true
            elseif data:unpack('b8', 43) == 4 then
                perm_gaze = false
            end
        end
    end
end)

windower.register_event('prerender', function()
    if not windower.ffxi.get_info().logged_in or not windower.ffxi.get_player() then -- stops prender if not loged in yet
        return
    end
    if perm_gaze or gaze then
        windower.ffxi.turn(windower.ffxi.get_mob_by_target('t').facing)
    elseif (windower.ffxi.get_player().in_combat and settings.auto_point and windower.ffxi.get_mob_by_target('t')) then
        windower.ffxi.turn((getAngle()+180):radian())--gets angle to the target
    end
end)
```

**Comment by KenshiDRK** [comment]
for triggered actor we need to change the id to index cause the 0x00E uses Index

**Comment by KenshiDRK** [comment]
what do you think about this?

https://gist.github.com/KenshiDRK/7639c5fe031352a48c5e64319016fa62

**Comment by smd111** [comment]
have you tested it??
if so that cool
but we still need a way to clear the triggers when a mob dies

**Comment by KenshiDRK** [comment]
Doing it now

**Comment by smd111** [comment]
in packet 0x00E this should be true if mob is dead packet['Mask'] == 0x20(i think)
but this is actualy a bit register
-- 0A   Bit 0: Position, Rotation, Walk Count
-- 0A   Bit 1: Claimer ID
-- 0A   Bit 2: HP, Status
-- 0A   Bit 3: Name
-- 0A   Bit 4:
-- 0A   Bit 5: The client stops displaying the mob when this bit is set (dead, out of range, etc.)
-- 0A   Bit 6:
-- 0A   Bit 7:
we want bit 5

we could check
if data:unpack('b8', 43) == 4 or packet['Mask'] == 0x20 then

**Comment by KenshiDRK** [comment]
It didn't working but I think it is due to getting a 0x00E packet with byte value 4 before the eyes are up so perm_gaze get set to false too quick, we have to delay the parsing of the packet.

**Comment by smd111** [comment]
how long do we need

**Comment by KenshiDRK** [comment]
not sure but I think 3 or 4 secs should be good

**Comment by smd111** [comment]
try this

```
    if id == 0x00E and perm_gaze then
        local packet = packets.parse('incoming', data)
        if packet.Index == perm_trigered_actor then
            if data:unpack('b8', 43) == 4 or packet['Mask'] == 0x20 then
                coroutine.sleep(3)
                perm_gaze = false
                perm_trigered_actor = 0
            end
        end
    end
```

i do need to know if it locks ffxi tho

**Comment by KenshiDRK** [comment]
coroutine.sleep doesn't work this way, cause I asked arcon when trying to delay a packet for a party buffs addon, we gotta think another way.

**Comment by KenshiDRK** [comment]
goin to try the coroutine in the check target action function

return true
coroutine.sleep(3)
perm_gaze = true

**Comment by KenshiDRK** [comment]
still not working I added a print and it never enters the
'if data:unpack('b8', 43) == 4 or packet['Mask'] == 0x20 then' check

**Comment by smd111** [comment]
how about

```
function perm_gaze_clear()
    perm_gaze = false
    perm_trigered_actor = 0
end


    if id == 0x00E and perm_gaze then
        local packet = packets.parse('incoming', data)
        if packet.Index == perm_trigered_actor then
            if data:unpack('b8', 43) == 4 or packet['Mask'] == 0x20 then
                coroutine.schedule(perm_gaze_clear, 3)
            end
        end
    end
```

i know this works because i use it in my gearswap includes

**Comment by KenshiDRK** [comment]
Im idiot I was modifiying the gaze_check on the github folder lol 1 min

**Comment by KenshiDRK** [comment]
Got it working!! I'll update the merge pull so you can rewiew

**Comment by smd111** [comment]
when ever your ready

**Comment by KenshiDRK** [comment]
I had to upper the schedule to 6 secs due to shah mat being a longer as shit animation, also I think they might be a problem with caturaes in a very weird case, for example a caturae gets up shield and shah mat at the same time and then shah mat wears off before the shield, then it won't turn cause the byte will be 06. what do you think?

**Comment by KenshiDRK** [comment]
I'll update the merge with a solution already, comment it if you see a better solution.

**Comment by smd111** [comment]
i think we will just have to bare it because i can think of a way to fix it

**Comment by KenshiDRK** [comment]
Here it is tested and working on the caturae, no time to test on peiste but there is no reason for it to not work.

**Comment by smd111** [comment]
ok but unless you want to get this back out you do not need to return this
    return perm_gaze

**Comment by smd111** [comment]
whats this about Possible conflict with auto_point??

nvm i see it now

**Comment by KenshiDRK** [comment]
Well time to sleep for me, if you see anything still wrong or some improvement comment it and I'll fix tomorrow, nn.

**Comment by smd111** [comment]
so far i can see nothing wrong

**Comment by smd111** [comment]
are thing still working for you??

**Comment by KenshiDRK** [comment]
Yes, its working but I caught some other bugs not related to the glowing eyes, also SE is swaping the monster abilities from the old ambuscade mobs with the new ones (I dunno why SE does it like this, it makes no sense) and need to change them for the new ones.

The bugs I caught are those:
1. check_facing() needs to be changed to be the packet['Actor'] instead of target or it could turn when fighting several mobs and the actor not being faced, but due to you being facing the target you will turn.
2. a few blood pacts share the same param than mob abilities (Flaming Crush, water 2 and soothing current, maybe more?) making the char to turn sometimes.  So need to had a check for pets, thats what I though:

```
function pet_check(packet)
    local actor = windower.ffxi.get_mob_by_id(packet['Actor'])
    local party_indices = {'p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'a10', 'a11', 'a12', 'a13', 'a14', 'a15', 'a20', 'a21', 'a22', 'a23', 'a24', 'a25'}
    local party = windower.ffxi.get_party()
    for i = 1, 18 do
        local member = party[party_indices[i]]
        if member and member.mob then
            if member.mob.pet_index and member.mob.pet_index == actor.index then
                return true
            end
        end
    end
    return false
end
```

Problem with this its it doesn't take into account pets from ppl outside ally, only solution to include pets outside ally is using the avatar names, but I prefer to avoid using names, maybe you can think of a better solution.

**Comment by smd111** [comment]
your pet it will have
windower.ffxi.get_mob_by_id(id).tp
this is every thing that windower.ffxi.get_mob_by_id(id) can give
    name: string
    claim_id: int
    distance: number
    facing: number
    hpp: int
    id: int
    is_npc: boolean
    mob_type: int
    model_size: number
    speed: number
    speed_base: number
    race: number
    status: int
    index: int
    x: number
    y: number
    z: number
    target_index: number (only valid for PCs)
    fellow_index: number (only valid for PCs)
    pet_index: number
    tp: number  (only valid for pets - May not exist?)
    mpp: number  (only valid for pets - May not exist?)
    charmed: boolean
    in_party: boolean
    in_alliance: boolean
    valid_target: boolean

mobs's should show something different

and i think ever mob id is below 2048

this is yet another reason i keep it limited to the players main target it makes it to complex
not to mention unless you aoe like mad thay cant build tp to hit you with gaze attacks

**Comment by KenshiDRK** [comment]
Even if you leave only to main target there is still a problem with soothing current cause you can be the target of the blood pact, I'll solve it and do a pull request, doing it probably by index, but need to know exactly whats the min index a player and pet can have.

**Comment by smd111** [comment]
if your looking for the short number i think its 2048 but im not sure

**Comment by KenshiDRK** [comment]
for index it needs to be lower cause my currrent index is 1117, for id might be true but we need to take out the zone from the id.

**Comment by smd111** [comment]
can you get the long id??
if this is true you got a not pc controled npc/mob??
string.format("%08x", longid):startswith("01"..string.format("%03x", windower.ffxi.get_info().zone))
--at lest you should i think

or this from gearswap

```
        local type = ""
        if player.id == mob_table.id then
            type  = 'SELF'
        elseif mob_table.is_npc then
            if mob_table.id%4096>2047 then
                type  = 'NPC'
            else
                type  = 'MONSTER'
            end
        else
            type  = 'PLAYER'
        end
```

**Comment by smd111** [comment]
local mob = windower.ffxi.get_mob_by_id(id)
if mob.is_npc and not mob.id%4096>2047 then
if false its a mob

**Comment by KenshiDRK** [comment]
you tested it?

**Comment by smd111** [comment]
no but it should be correct

**Comment by KenshiDRK** [comment]
not working it turned on flaming crush

**Comment by KenshiDRK** [comment]
I'm goin to go with mob.index > 1000 for now till I know a exact response

**Comment by KenshiDRK** [comment]
Got confirmed player index starts at 1024 and pets are even bigger indexes so mob.index > 1024 works realy good, tested it.

**Comment by KenshiDRK** [comment]
I'll put a pull request soon

**Comment by smd111** [comment]
ok

**Pull request merged**
