### PR TITLE
Few bug fixes

### PR DESCRIPTION
**Pull request by KenshiDRK**
fix for bug with pets and check_facing function changed to use packet
actor instead of target

### CODE REVIEW

**Comment by smd111** [comment]
thanks

**Comment by smd111** [comment]
i did a little reworking of the code to clean it up have a look
this will also allow use to add perm gazes eaiser then before

**Comment by KenshiDRK** [comment]
we could even use T{} on ender.

```
perm_gaze_control = {["Peiste"]={skills=T{2156, 2392},delay=3,ender=T{4}},
                    ["Caturae"]={skills=T{2776},delay=6,ender=T{4, 6}},}

if Table and (Table.ender:contains(effect) or packet['Mask'] == 0x20) then

```

**Comment by smd111** [comment]
i did not think of that
so ill change it to that

**Comment by smd111** [comment]
can you run this one and see if it still works for perm gaze
http://pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
The break on the check_target_action causes a "attemp to call a string value" error

**Comment by smd111** [comment]
whats that actual error it gives

**Comment by KenshiDRK** [comment]
Can't load the lua: lua runtime error: attemp to call a string value

**Comment by smd111** [comment]
try this one
http://pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
its turning on every action due to valid_action always having a value,  valid_action ~= "" solved it but it was turning back on shah mat before the eyes where off dunno why

**Comment by smd111** [comment]
i fixed that as well
ok i fixed the loading issues and put a new version here
pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
thats the one I was trying

**Comment by smd111** [comment]
it has the same url but its different thats the way pastebin works

```
           --new
            local valid_action = check_target_action(packet) or false
            if valid_action then
                if packet['Category'] == 7 and not pet_check(packet['Actor']) and (check_target_id(packet) or check_facing(packet['Actor'])) then

            --old
            local valid_action = check_target_action(packet)
            if packet['Category'] == 7 and not pet_check(packet['Actor']) and (check_target_id(packet) or check_facing(packet['Actor'])) and valid_action then
```

**Comment by smd111** [comment]
what im trying to do is clean up the code
by reordering thing so redundancies can be removed

**Comment by KenshiDRK** [comment]
now it won't turn when eyes get off

**Comment by smd111** [comment]
is that perm or normal
any errors showing

**Comment by KenshiDRK** [comment]
perm

**Comment by smd111** [comment]
i dont see what would cause that

**Comment by KenshiDRK** [comment]
yea I don't see it either

**Comment by smd111** [comment]
try this one

**Comment by KenshiDRK** [comment]
I can't see a link

**Comment by smd111** [comment]
the same as above
http://pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
Still not turned,  added print statements and its not passing if packet.Index == perm_trigered_actor then of the 0x00e packet

**Comment by smd111** [comment]
put this in just befor that
print(packet.Index,perm_trigered_actor)

**Comment by KenshiDRK** [comment]
yea perm_trigered_actor is being 0

**Comment by smd111** [comment]
try this one
http://pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
still not turning and I don't see why but it seem its not setting the valid_action right

**Comment by smd111** [comment]
last one 
http://pastebin.com/2NRTaGZX

**Comment by KenshiDRK** [comment]
It has an error on check_facing cause it tried to call a table, after solving it now it turns back before the eyes are up >.<, Im done with testing for today.

**Comment by smd111** [comment]
thanks for testing thoes ill upload a new version now

**Comment by KenshiDRK** [comment]
Also Gist is a lot better than pastebin

**Comment by smd111** [comment]
i know but i did not want to change the working version just incase of big buggs
i also increased the version # to 2.0

**Comment by KenshiDRK** [comment]
with gist you don't need to change the working version, https://gist.github.com/
Its independent from the github repositories its like a pastebin

**Comment by smd111** [comment]
i gave you Collaborators status for gaze check if you find a bug or want to add something to it

**Comment by KenshiDRK** [comment]
After sleeping and seeing things cleared, the last commit still doesn't work because of this 
line 126 to 128

```
if not perm_gaze then
    windower.ffxi.turn:schedule(1,windower.ffxi.get_mob_by_target('t').facing+math.pi)
end
```

perm_gaze is not set to true till the coroutine do his work so when the action packet of category 11 is received the perm_gaze is still false making it to turn on perm gazes when it shouldn't

**Comment by KenshiDRK** [comment]
so probably solving this issue could make the reworking code of yesterday to work

**Comment by smd111** [comment]
you have rights to change the repos code(at lest you should)
i moved that back in to gaze

**Comment by KenshiDRK** [comment]
do you still have a version of the reworking code of yesterday?

no

**Pull request merged**
